// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using theclimber;

namespace sdgreacttemplate.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20190703142553_removed two tables and simplified data")]
    partial class removedtwotablesandsimplifieddata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("theclimber.Models.Climb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Directions");

                    b.Property<int>("Height");

                    b.Property<string>("Location");

                    b.Property<string>("Notes");

                    b.Property<string>("Rating");

                    b.Property<string>("RouteName");

                    b.Property<bool>("SportGear");

                    b.Property<int>("Ticks");

                    b.Property<bool>("TradGear");

                    b.HasKey("Id");

                    b.ToTable("Climbs");
                });
#pragma warning restore 612, 618
        }
    }
}
